default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: postgres
  password: new_password
  template: template0

development:
  <<: *default
  database: zabaan_development

staging:
  <<: *default
  database: zabaan_staging

production:
  <<: *default
  database: zabaan_production

test:
  <<: *default
  database: zabaan_test

  # pg_dump -i -h localhost -U postgres -d vianaar_data_migration_1 data_migration_dump.sql
  # psql -h localhost -U postgres -d vianaar_development_1_aug -f lead_hero_staging_1aug2025.sql
